ADRES EKRANI SENARYOLARI
========================
     
Adres Bilgileri Ekleme Senaryosu
--------------------------------
tags:addAdress
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* ADRESLERİM BUTONUNA TIKLANIYOR
* ADRESLERİM SAYFASI KONTROL EDİLİYOR
* KAYITLI ADRES SAYISI KONTROL EDİLİYOR
* YENİ ADRES EKLEME BUTONUNA TIKLANIYOR
* ADRES EKLEME EKRANI KONTROL EDİLİYOR
* ADRES BİLGİLERİ BUTONUNA TIKLANIYOR
* ADRES EKRANI KONTROL EDİLİYOR
* FATURA TİPİ SEÇİLİYOR
* ADRES BİLGİLERİ DOLDURULUYOR
* ADRES BİLGİLERİ KONTROL EDİLİYOR
* KAYDET BUTONUNA TIKLANIYOR
* KAYITLI ADRES SAYILARI KARŞILAŞTIRILIYOR

Adres Bilgileri Boş Bırakma Senaryosu
-------------------------------------
tags:emptyAdress
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* ADRESLERİM BUTONUNA TIKLANIYOR
* ADRESLERİM SAYFASI KONTROL EDİLİYOR
* YENİ ADRES EKLEME BUTONUNA TIKLANIYOR
* ADRES EKLEME EKRANI KONTROL EDİLİYOR
* ADRES BİLGİLERİ BUTONUNA TIKLANIYOR
* ADRES EKRANI KONTROL EDİLİYOR
* KAYDET BUTONUNA TIKLANIYOR
* ADRES SAYFASI HATA MESAJLARI KONTROL EDİLİYOR




