Sepet Sayfası Senaryoları
=========================

Logout Durumunda Satın Alma Senaryosu
-------------------------------------
tags:LogoutDurumundaSatinAlmaSenaryosu
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SATIN AL BUTONUNA TIKLANIYOR
* SAYFA KONTROL EDİLİYOR

Login Durumunda Satın Alma Senaryosu
------------------------------------
tags:LoginDurumundaSatinAlmaSenaryosu
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SATIN AL BUTONUNA TIKLANIYOR
* ADRES SAYFASI KONTROL EDİLİYOR
* ADRES SAYFASINDA DEVAM ET BUTONUNA TIKLANIYOR
* SATIN ALMA SAYFASI KONTROL EDİLİYOR

Sepetteki Ürün Sayısını Arttırma Senaryosu
------------------------------------------
tags:UrunSayisiArttirma
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SEPETTEKİ ÜRÜN SAYISI ARTTIRILIYOR
* ÜRÜN SAYISI ARTIŞI KONTROL EDİLİYOR

