END TO END SENARYOSU
====================
     
Happy Path
----------
tags:happyPath
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SEPETTEKİ ÜRÜN SAYISI ARTTIRILIYOR
* ÜRÜN SAYISI ARTIŞI KONTROL EDİLİYOR
* ADRESLERİM BUTONUNA TIKLANIYOR
* ADRESLERİM SAYFASI KONTROL EDİLİYOR
* KAYITLI ADRES SAYISI KONTROL EDİLİYOR
* YENİ ADRES EKLEME BUTONUNA TIKLANIYOR
* ADRES EKLEME EKRANI KONTROL EDİLİYOR
* ADRES BİLGİLERİ BUTONUNA TIKLANIYOR
* ADRES EKRANI KONTROL EDİLİYOR
* FATURA TİPİ SEÇİLİYOR
* ADRES BİLGİLERİ DOLDURULUYOR
* ADRES BİLGİLERİ KONTROL EDİLİYOR
* KAYDET BUTONUNA TIKLANIYOR
* KAYITLI ADRES SAYILARI KARŞILAŞTIRILIYOR
* ANA SAYFADAN SEPETE GİDİLİYOR
* SATIN AL BUTONUNA TIKLANIYOR
* ADRES SAYFASI KONTROL EDİLİYOR
* ADRES SAYFASINDA DEVAM ET BUTONUNA TIKLANIYOR
* SATIN ALMA SAYFASI KONTROL EDİLİYOR
* KART ÜZEİRNDEKİ İSİM DOLDURULUYOR
* KART ÜZERİNDEKİ İSİM KONTROL EDİLİYOR
* KART NUMARASI DOLDURULUYOR
* KART NUMARASI KONTROL EDİLİYOR
* SON KULLANMA TARİHİ AY DOLDURULUYOR
* SON KULLANMA TARİHİ YIL DOLDURULUYOR
* CVV ALANI DOLDURULUYOR
* CVV ALANI KONTROL EDİLİYOR
* TAKSİT SEÇENEĞİ SEÇİLİYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* SİPARİŞ ÖZET SAYFASI KONTROL EDİLİYOR
* SİTEDE GERİ GİDİLİYOR
* ÖNCEKİ SAYFA KONTROL EDİLİYOR
* ÇIKIŞ YAP BUTONUNA TIKLANIYOR
* LOGOUT İŞLEMİ KONTROL EDİLİYOR