GİRİŞ EKRANI SENARYOLARI
========================

Başarılı Login Senaryosu
------------------------
tags:BasariliLogin
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR

Doğru Mail Yanlış Şifre Senaryosu
---------------------------------
tags:DogruMailYanlisSifre
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* MAİL DOĞRU ŞİFRE YANLIŞ GİRİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN SAYFASI HATA MESAJI 1 KONTROL EDİLİYOR

Yanlış Mail Doğru Şifre Senaryosu
---------------------------------
tags:YanlisMailDogruSifre
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* MAİL YANLIŞ ŞİFRE DOĞRU GİRİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN SAYFASI HATA MESAJI 1 KONTROL EDİLİYOR

Mail ve Şifre Alanları Boş Bırakma Senaryosu
--------------------------------------------
tags:AlanlarBosBirakiliyor
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN SAYFASI HATA MESAJI 2 KONTROL EDİLİYOR


Logout Senaryosu
----------------
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* ÇIKIŞ YAP BUTONUNA TIKLANIYOR
* LOGOUT İŞLEMİ KONTROL EDİLİYOR



