ÖDEME EKRANI SENARYOLARI
========================
     
Kart Bilgileri Boş Bırakma Senaryosu
------------------------------------
tags:KartBilgileriBosBirakmaSenaryosu
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SATIN AL BUTONUNA TIKLANIYOR
* ADRES SAYFASI KONTROL EDİLİYOR
* ADRES SAYFASINDA DEVAM ET BUTONUNA TIKLANIYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 1 KONTROL EDİLİYOR
* KART ÜZEİRNDEKİ İSİM DOLDURULUYOR
* KART ÜZERİNDEKİ İSİM KONTROL EDİLİYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 2 KONTROL EDİLİYOR
* KART NUMARASI DOLDURULUYOR
* KART NUMARASI KONTROL EDİLİYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 3 KONTROL EDİLİYOR
* SON KULLANMA TARİHİ AY DOLDURULUYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 4 KONTROL EDİLİYOR
* SON KULLANMA TARİHİ YIL DOLDURULUYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 5 KONTROL EDİLİYOR
* CVV ALANI DOLDURULUYOR
* CVV ALANI KONTROL EDİLİYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 6 KONTROL EDİLİYOR

Eksik Kart Numarası Senaryosu
-----------------------------
tags:EksikKartNumarasiSenaryosu
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* KULLANICI BİLGİLERİ KONTROL EDİLİYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SATIN AL BUTONUNA TIKLANIYOR
* ADRES SAYFASI KONTROL EDİLİYOR
* ADRES SAYFASINDA DEVAM ET BUTONUNA TIKLANIYOR
* KART ÜZEİRNDEKİ İSİM DOLDURULUYOR
* SON KULLANMA TARİHİ AY DOLDURULUYOR
* SON KULLANMA TARİHİ YIL DOLDURULUYOR
* CVV ALANI DOLDURULUYOR
* TAKSİT SEÇENEĞİ SEÇİLİYOR
* KART NUMARASI EKSİK DOLDURULUYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 2 KONTROL EDİLİYOR

Yanlış CVV Senaryosu
--------------------
tags:YanlisCVVSenaryosu
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* GİRİŞ YAP BUTONUNA TIKLANIYOR
* KULLANICI BİLGİLERİ DOĞRU DOLDURULUYOR
* GİRİŞ SAYFASINDAKİ GİRİŞ YAP BUTONUNA TIKLANIYOR
* LOGİN İŞLEMİ KONTROL EDİLİYOR
* RASTGELE ÜRÜN SEÇİLİYOR
* SEÇİLEN ÜRÜN KONTROL EDİLİYOR
* SEÇİLEN ÜRÜN SEPETE EKLENİYOR
* SEPETE EKLEME İŞLEMİ KONTROL EDİLİYOR
* SEPETE GİDİLİYOR
* SEPET SAYFASI KONTROL EDİLİYOR
* SATIN AL BUTONUNA TIKLANIYOR
* ADRES SAYFASI KONTROL EDİLİYOR
* ADRES SAYFASINDA DEVAM ET BUTONUNA TIKLANIYOR
* KART ÜZEİRNDEKİ İSİM DOLDURULUYOR
* SON KULLANMA TARİHİ AY DOLDURULUYOR
* SON KULLANMA TARİHİ YIL DOLDURULUYOR
* TAKSİT SEÇENEĞİ SEÇİLİYOR
* CVV EKSİK DOLDURULUYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 5 KONTROL EDİLİYOR
* CVV FAZLA DOLDURULUYOR
* ÖDEME SAYFASINDA DEVAM ET BUTONUNA BASILIYOR
* ÖDEME SAYFASI HATA MESAJI 5 KONTROL EDİLİYOR











