ÜYELİK EKRANI SENARYOLARI
=========================

Üyelik Bilgileri Boş Bırakma Senaryosu
--------------------------------------
tags:UyelikBilgileriBosBirakmaSenaryosu
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* ÜYE OL BUTONUNA TIKLANIR
* ÜYE KAYIT SAYFASI KONTROL EDİLİR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 1 KONTROL EDİLİR
* ADINIZ ALANI DOLDURULUR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 2 KONTROL EDİLİR
* SOYADINIZ BÖLÜMÜN DOLDURULUR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 3 KONTROL EDİLİR
* E POSTA ALANI DOLDURULUR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 4 KONTROL EDİLİR
* ŞİFRE ALANI DOLDURULUR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 5 KONTROL EDİLİR
* ÜYELİK SÖZLEŞMESİ BUTONUNA TIKLANIR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 6 KONTROL EDİLİR

Geçersiz E-Posta Senaryosu
--------------------------
tags:GecersizEposta
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* ÜYE OL BUTONUNA TIKLANIR
* ÜYE KAYIT SAYFASI KONTROL EDİLİR
* ADINIZ ALANI DOLDURULUR
* SOYADINIZ BÖLÜMÜN DOLDURULUR
* GEÇERSİZ E POSTA GİRİLİR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 7 KONTROL EDİLİR

Geçersiz Şifre Senaryosu
------------------------
tags:GecersizSifre
* SİTE AÇILIYOR
* SİTE KONTROL EDİLİYOR
* ÜYE OL BUTONUNA TIKLANIR
* ÜYE KAYIT SAYFASI KONTROL EDİLİR
* ADINIZ ALANI DOLDURULUR
* SOYADINIZ BÖLÜMÜN DOLDURULUR
* E POSTA ALANI DOLDURULUR
* 6 KARAKTERDEN KISA ŞİFRE GİRİLİR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 8 KONTROL EDİLİR
* 6 KARAKTERDEN UZUN ANCAK RAKAM İÇERMEYEN ŞİFRE GİRİLİR
* ÜYELİK SÖZLEŞMESİ BUTONUNA TIKLANIR
* AYDINLATMA METNİ BUTONUNA TIKLANIR
* KAYIT SAYFASINDAKİ ÜYE OL BUTONUNA TIKLANIR
* KAYIT SAYFASI HATA MESAJI 8 KONTROL EDİLİR




















